# -*- coding: utf-8 -*-
"""11w_crawling_beau_학생1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rbq9W82zLVBLxWmVvwtNJ2NzfVzWdM5n
"""

!pip install beautifulsoup4
!pip install requests

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/Colab Notebooks/11w_crawling/
!pwd
!ls

import requests
from bs4 import BeautifulSoup

url = 'https://movie.naver.com/movie/sdb/rank/rmovie.naver'

response = requests.get(url)

if response.status_code == 200:
  html = response.text
  soup = BeautifulSoup(html, 'html.parser')
  print(soup)
else :
  print(response.status_code)

movies = soup.select('#old_content > table > tbody > tr')

for movie in movies :
  a_rank = movie.select_one('td.ac > img')
  a_tag = movie.select_one('td.title > div > a')
  if a_rank is not None:
    rank, title = a_rank['alt'], a_tag.text
    print(rank,title)